import * as os from 'os';
import * as fs from 'fs';
import { join } from 'path';
import { deleteAgentFromLibrary, getAgentsFromLibrary, saveAgentToLibrary } from './agentLibraryStorage';
import { LibraryEntry, LIBRARY_SCHEMA_VERSION } from '../../shared/agentLibrary';

function assert(condition: boolean, message: string) {
    if (!condition) {
        console.error(`❌ FAILED: ${message}`);
        process.exit(1);
    } else {
        console.log(`✅ PASSED: ${message}`);
    }
}

function runTests() {
    console.log('Starting Agent Library Storage Tests...');

    const tmpDir = fs.mkdtempSync(join(os.tmpdir(), 'agentlib-'));
    const legacyAgent = {
        id: 'agent-test',
        timestamp: new Date().toISOString(),
        generation: 10,
        metrics: { A: 0.8, C: 0.2, D: 0.4, alertRate: 0.1 },
        parameters: { k_AC: 0.1 },
        environmentalControl: { U: 0.2 },
        historySnippet: [],
        validationMetrics: {
            stateBoundsViolationRate: 0,
            diversityFloorViolationFraction: 0,
            controlBoundsViolationRate: 0
        },
        runContext: { bestAgencySoFar: 0.8 },
        name: 'Test Agent',
        description: 'Unit test agent',
        tags: ['Test']
    };

    const saveLegacyResult = saveAgentToLibrary(tmpDir, legacyAgent);
    assert(saveLegacyResult.success, 'Legacy agent saved to library');

    const v2Entry: LibraryEntry = {
        schemaVersion: LIBRARY_SCHEMA_VERSION,
        id: 'agent-v2',
        createdAt: new Date().toISOString(),
        scenario: {
            id: 'sde-v1',
            name: 'SDE Macro-Dynamics (v1)',
            type: 'sde',
            version: '1.0.0'
        },
        metricsAtEmergence: {
            A: 0.9,
            C: 0.3,
            D: 0.5,
            U: 0.2,
            alertRate: 0.1,
            generation: 20
        },
        alertDetails: {
            threshold: 0.75,
            confidence: 0.95,
            triggerType: 'threshold'
        },
        xenobiologistReport: {
            name: 'Test V2 Agent',
            specSheet: 'Generated by tests',
            tags: ['Test', 'V2']
        }
    };

    const saveV2Result = saveAgentToLibrary(tmpDir, v2Entry as any);
    assert(saveV2Result.success, 'V2 agent saved to library');

    const listAfterSave = getAgentsFromLibrary(tmpDir);
    assert(listAfterSave.length === 2, 'Agent list contains saved agents');
    assert(listAfterSave.some(a => a.id === 'agent-test'), 'Legacy agent id matches');
    assert(listAfterSave.some(a => a.id === 'agent-v2'), 'V2 agent id matches');
    assert(listAfterSave.every(a => a.schemaVersion === LIBRARY_SCHEMA_VERSION), 'Agents migrated to current schema');

    const deleteLegacy = deleteAgentFromLibrary(tmpDir, 'agent-test');
    assert(deleteLegacy.success, 'Legacy agent deleted from library');

    const deleteV2 = deleteAgentFromLibrary(tmpDir, 'agent-v2');
    assert(deleteV2.success, 'V2 agent deleted from library');

    const listAfterDelete = getAgentsFromLibrary(tmpDir);
    assert(listAfterDelete.length === 0, 'Agent list empty after delete');

    console.log('All agent library storage tests passed!');
}

runTests();
