/**
 * Simulation Types for Open-Ended Virtual Evolution Simulator
 * Based on the SDE model from the PRD schema
 */

/** State variables of the simulation (all normalized 0-1) */
export interface SimulationState {
    /** Normalized ecosystem algorithmic complexity proxy */
    C: number;
    /** Normalized ecological diversity proxy */
    D: number;
    /** Normalized agency score proxy */
    A: number;
    /** Alert rate (derived from A crossing threshold) */
    alertRate: number;
    /** Current generation/timestep */
    generation: number;
}

/** Control signal applied by researcher */
export interface ControlSignal {
    /** Environment difficulty/novelty control (0-1) */
    U: number;
}

/** SDE Model Parameters */
export interface SimulationParameters {
    /** Diversity-to-complexity coupling rate (1/generation) */
    k_CD: number;
    /** Complexity-to-agency coupling rate (1/generation) */
    k_AC: number;
    /** Difficulty-driven selection pressure (1/generation) */
    k_DU: number;
    /** Difficulty-driven stimulation term (1/generation) */
    k_U: number;
    /** Stochasticity scale on complexity dynamics */
    sigma_C: number;
    /** Stochasticity scale on diversity dynamics */
    sigma_D: number;
    /** Stochasticity scale on agency dynamics */
    sigma_A: number;
    /** Alert rate time constant */
    tau: number;
    /** Sigmoid sharpness for alert calculation */
    eps: number;
    /** Agency alert threshold */
    A_alert: number;
    /** Timestep size (generations) */
    dt: number;
    /** Whether to use GPU for compute (Ensemble Mode) */
    useGPU?: boolean;

    // New tunable coefficients
    /** Complexity decay rate (default 0.3) */
    k_C_decay: number;
    /** Diversity intrinsic growth rate (default 0.25) */
    k_D_growth: number;
    /** Diversity decay rate coefficient (default 0.15) */
    k_D_decay: number;
    /** Agency coupling to Difficulty (default 0.4) */
    k_AU: number;
    /** Agency decay rate (default 0.35) */
    k_A_decay: number;
}

/** Known quantities from the PRD */
export interface KnownQuantities {
    /** World lattice size for spatial interactions */
    N_cells: number;
    /** Telemetry aggregation timestep */
    dt: number;
    /** Compute budget (GPUs) */
    B_gpu: number;
    /** Run length in generations */
    T_horizon: number;
    /** Agency alert threshold */
    A_alert: number;
}

/** Telemetry data point for charting */
export interface TelemetryPoint {
    generation: number;
    C: number;
    D: number;
    A: number;
    U: number;
    alertRate: number;
}

/** Alert event when agency crosses threshold */
export interface AlertEvent {
    id: string;
    generation: number;
    agencyLevel: number;
    timestamp: Date;
    type: 'threshold_crossed' | 'sustained_high' | 'peak';
}

/** History entry for AI actions */
export interface AIHistoryEntry {
    generation: number;
    action: string;
    u: number;
    params?: Partial<SimulationParameters>;
    reasoning: string;
    outcome: {
        A_before: number;
        A_after: number;
        delta_A: number;
    };
}

/** Log entry for any intervention (Manual or AI) */
export interface InterventionLogEntry {
    id: string;
    timestamp: number; // generation
    realtime: Date;
    source: 'USER' | 'AI';
    action: string;
    reasoning?: string;
}

/** Saved Agent Structure for Library */
export interface SavedAgent {
    id: string;
    timestamp: string; // ISO String
    name: string; // generated by AI
    description: string; // generated by AI spec sheet
    tags: string[]; // e.g. "High-Agency", "Stable", "Burst"

    // Snapshot of emergence state
    generation: number;
    metrics: {
        A: number;
        C: number;
        D: number;
        alertRate: number;
    };

    // The "DNA"
    parameters: SimulationParameters;

    // Context
    environmentalControl: ControlSignal;
    historySnippet: AIHistoryEntry[]; // Last few actions leading to emergence

    // Additional Context for AI Analysis
    validationMetrics: ValidationMetrics;
    runContext: {
        bestAgencySoFar: number;
    };
}

/** Validation metrics from the PRD */
export interface ValidationMetrics {
    stateBoundsViolationRate: number;
    diversityFloorViolationFraction: number;
    controlBoundsViolationRate: number;
}

/** Default initial conditions from the PRD */
export const DEFAULT_INITIAL_STATE: SimulationState = {
    C: 0.05,
    D: 0.6,
    A: 0.02,
    alertRate: 0,
    generation: 0
};

/** Default parameters from the PRD */
export const DEFAULT_PARAMETERS: SimulationParameters = {
    k_CD: 0.12,
    k_AC: 0.10,
    k_DU: 0.35,
    k_U: 0.08,
    sigma_C: 0.005, // Lowered for stability as per log findings
    sigma_D: 0.02,
    sigma_A: 0.005, // Lowered for stability
    tau: 5,
    eps: 0.05,
    A_alert: 0.75, // Updated target
    dt: 0.1,
    useGPU: false,

    // New defaults matching original hardcoded values
    k_C_decay: 0.3,
    k_D_growth: 0.25,
    k_D_decay: 0.15,
    k_AU: 0.4,
    k_A_decay: 0.35
};

/** Default control signal */
export const DEFAULT_CONTROL: ControlSignal = {
    U: 0.2
};

/** 
 * SCENARIO SYSTEM TYPE DEFINITIONS (v2.0) checks
 */

export interface ScenarioMetadata {
    id: string;
    name: string;
    description: string;
    version: string;
    type: 'sde' | 'math' | 'alignment' | 'bio';
}

/**
 * Common events emitted by any scenario
 */
export type ScenarioEventType =
    | 'threshold_crossed'
    | 'sustained_high'
    | 'peak'
    | 'task_solved'
    | 'constraint_violated'
    | 'extinction'
    | 'intervention'
    | 'custom';

export interface ScenarioEvent {
    type: ScenarioEventType;
    timestamp: number; // generation or time
    data: any;
    message: string;
}

export interface Scenario<ConfigType = any> {
    metadata: ScenarioMetadata;

    /** Initialize the scenario with a seed and configuration */
    initialize(seed: number, config?: ConfigType): void;

    /** Advance the simulation by one step */
    step(control: ControlSignal): void;

    /** Update configuration mid-run */
    updateConfig(config: Partial<ConfigType>): void;

    /** Get the current telemetry metrics */
    getMetrics(): TelemetryPoint;

    /** Get the current internal state (for UI/visualizers) */
    getState(): any;

    /** Serialize complete state for snapshot/replay */
    serialize(): string;

    /** Restore state from snapshot */
    deserialize(state: string): void;

    /** Get recent events */
    getEvents(): ScenarioEvent[];

    /** Clear event queue */
    clearEvents(): void;
}
